# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='slug',
        ),
        migrations.AddField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('archived', 'Archived')], default='pending', max_length=200, verbose_name='Status'),
        ),
    ]
